version: "3.3"

services:
    nodejs:
        build:
          context: .
          dockerfile: ./.docker/Dockerfile
        container_name: "nodejs"
        restart: unless-stopped
        env_file: ./.env
        environment:
          APP_NAME: ${APP_NAME}
          ENVIRONMENT: ${ENVIRONMENT}
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        ports:
          - '${NODE_PORT}:${NODE_PORT}'
        volumes:
          - ./code:/opt/code/
