version: "3.3"

services:
    db:
        image: mariadb:latest
        container_name: "db"
        restart: unless-stopped
        env_file: ./.env
        ports:
          - '3306:3306'
        environment:
          MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
          MARIADB_USER: ${DATABASE_USERNAME}
          MARIADB_PASSWORD: ${DATABASE_PASSWORD}
          DATABASE_APP: ${APP_DATABASE}
        volumes:
          - ./storage:/var/lib/mysql

    adminer:
        image: adminer:latest
        container_name: "adminer"
        restart: unless-stopped
        env_file: ./.env
        ports:
          - '${ADMINER_PORT}:8080'
        depends_on:
          - db

    nodejs:
        build:
          context: .
          dockerfile: ./.docker/Dockerfile
        container_name: "nodejs"
        restart: unless-stopped
        env_file: ./.env
        environment:
          APP_NAME: ${APP_NAME}
          ENVIRONMENT: ${ENVIRONMENT}
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        ports:
          - '${NODE_PORT}:${NODE_PORT}'
        volumes:
          - ./code:/opt/code/
